backend:
  name: git-gateway
  branch: main # Senin github branch adın (main veya master)
  site_url: https://www.blueemberorg.com
media_folder: "public/images/uploads" # Resimleri nereye fiziksel olarak yüklesin
public_folder: "/images/uploads" # Sitede resim yolu nasıl görünsün

collections:
  - name: "blogs" # Kod tarafındaki ID
    label: "Blog Yazıları" # Panelde görünen isim
    folder: "content/blogs" # Markdown dosyalarını buraya kaydedecek
    create: true # Yeni yazı eklemeye izin ver
    slug: "{{slug}}" # Dosya ismini slug olarak kaydet
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Kapak Resmi", name: "image", widget: "image"}
      - {label: "Okuma Süresi", name: "time", widget: "string", hint: "Örn: 5 dk okuma"}
      - {label: "Puan", name: "rating", widget: "number", value_type: "float", step: 0.1, min: 0, max: 5}
      - {label: "İçerik", name: "body", widget: "markdown"}